module.exports = {
    SELECT_ORG : 'SELECT_ORG',
    INVALIDATE_ORG : 'INVALIDATE_ORG',
    RECEIPT_ORG : 'RECEIPT_ORG',
    ASK_ORG : 'ASK_ORG',

    INVALIDATE_PRJ : 'INVALIDATE_PRJ',
    ASK_PRJ_LIST : 'ASK_PRJ_LIST',
    RECEIPT_PRJ_LIST : 'RECEIPT_PRJ_LIST',
    SELECT_PRJ : 'SELECT_PRJ',

    SHOW_FUNCTPROCESSESDATAMOVES_GRID : 'SHOW_FUNCTPROCESSESDATAMOVES_GRID'
    
}
