module.exports = {
    REQUEST_POSTS : 'REQUEST_POSTS',
    RECEIVE_POSTS : 'RECEIVE_POSTS',
    SELECT_SUBREDDIT : 'SELECT_SUBREDDIT',
    INVALIDATE_SUBREDDIT : 'INVALIDATE_SUBREDDIT',

    SELECT_ORG : 'SELECT_ORG',
    INVALIDATE_ORG : 'INVALIDATE_ORG',
    RECEIPT_ORG : 'RECEIPT_ORG',
    ASK_ORG : 'ASK_ORG',

    INVALIDATE_PRJ : 'INVALIDATE_PRJ',
    ASK_PRJ_LIST : 'ASK_PRJ_LIST',
    RECEIPT_PRJ_LIST : 'RECEIPT_PRJ_LIST',
    SELECT_PRJ : 'SELECT_PRJ',

    DEMANDE_DOC : 'DEMANDE_DOC',
    RECEPTION_DOC : 'RECEPTION_DOC',
    SELECT_SECTION : 'SELECT_SECTION',
    CHANGE_DISPLAY: 'CHANGE_DISPLAY',

    INVALIDATE_SECTION : 'INVALIDATE_SECTION',
    RECEIVE_SECTION : 'RECEIVE_SECTION',
    REQUEST_SECTION : 'REQUEST_SECTION',

    
    CREATE_SECTION : 'CREATE_NODE',
    DELETE_SECTION : 'DELETE_NODE',
    ADD_CHILD : 'ADD_CHILD',
    REMOVE_CHILD : 'REMOVE_CHILD'
    
}
